import Head from "next/head";
import BlogBannerSection from "@/components/pages/blog/BlogBannerSection";
import BlogListSection from "@/components/pages/blog/BlogListSection";

export default function Blog() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <BlogBannerSection />
        <BlogListSection />
      </main>
    </>
  )
}
