import Head from "next/head";
import ServicesBannerSection from "@/components/pages/services/ServicesBannerSection";
import ServicesCategorySection from "@/components/pages/services/ServicesCategorySection";
import ProcessSection from "@/components/process";
import ServiceDesignSection from "@/components/pages/services/ServiceDesignSection";
import ServiceDevelopmentSection from "@/components/pages/services/ServiceDevelopmentSection";
import ServicePowerUpSection from "@/components/pages/services/ServicePowerUpSection";
import Contactus from "@/components/contact-us";

export default function Services() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <ServicesBannerSection />
        <ServicesCategorySection />
        <ProcessSection />
        <ServiceDesignSection />
        <ServiceDevelopmentSection />
        <ServicePowerUpSection />
        <Contactus />
      </main>
    </>
  )
}
