import Head from "next/head";
import Contactus from "@/components/contact-us";
import ArchitectureDesignBannerSection
  from "@/components/pages/design/architecture-design/ArchitectureDesignBannerSection";
import ArchitectureDesignCategorySection
  from "@/components/pages/design/architecture-design/ArchitectureDesignCategorySection";
import ArchitectureDesignSoftwareSection from "@/components/pages/design/architecture-design/ArchitectureDesignSoftwareSection";
import ArchitectureDesignInterfaceSection
  from "@/components/pages/design/architecture-design/ArchitectureDesignInterfaceSection";
import ArchitectureDesignNextServiceSection
  from "@/components/pages/design/architecture-design/ArchitectureDesignNextServiceSection";

export default function UiDesign() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Architecture Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <ArchitectureDesignBannerSection />
        <ArchitectureDesignCategorySection />
        <ArchitectureDesignSoftwareSection />
        <ArchitectureDesignInterfaceSection />
        <ArchitectureDesignNextServiceSection />
        <Contactus />
      </main>
    </>
  )
}
