import Head from "next/head";
import Contactus from "@/components/contact-us";
import ContactBannerSection from "@/components/pages/contact/ContactBannerSection";

export default function Projects() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <ContactBannerSection />
        <Contactus />
      </main>
    </>
  )
}
