import Head from "next/head";
import InfrastructureBannerSection from "@/components/pages/power-up/infrastructure/InfrastructureBannerSection";
import InfrastructureCategorySection from "@/components/pages/power-up/infrastructure/InfrastructureCategorySection";
import InfrastructureCloudSection from "@/components/pages/power-up/infrastructure/InfrastructureCloudSection";
import InfrastructurePublishingSection
  from "@/components/pages/power-up/infrastructure/InfrastructurePublishingSection";
import InfrastructureNextServiceSection
  from "@/components/pages/power-up/infrastructure/InfrastructureNextServiceSection";
import Contactus from "@/components/contact-us";

export default function Infrastructure() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Infrastructure</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <InfrastructureBannerSection />
        <InfrastructureCategorySection />
        <InfrastructureCloudSection />
        <InfrastructurePublishingSection />
        <InfrastructureNextServiceSection />
        <Contactus />
      </main>
    </>
  )
}
