import Head from "next/head";
import PowerUpBannerSection from "@/components/pages/power-up/PowerUpBannerSection";
import PowerUpCategorySection from "@/components/pages/power-up/PowerUpCategorySection";
import PowerUpSecureSection from "@/components/pages/power-up/PowerUpSecureSection";
import PowerUpSecuritySection from "@/components/pages/power-up/PowerUpSecuritySection";
import PowerUpScalabilitySection from "@/components/pages/power-up/PowerUpScalabilitySection";
import PowerUpAvailabilitySection from "@/components/pages/power-up/PowerUpAvailableSection";
import PowerUpNextServiceSection from "@/components/pages/power-up/PowerUpNextServiceSection";
import Contactus from "@/components/contact-us";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";

export default function PowerUp() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Power up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <PowerUpBannerSection />
        <PowerUpCategorySection />
        <PowerUpSecureSection />
        <PowerUpSecuritySection />
        <PowerUpScalabilitySection />
        <PowerUpAvailabilitySection />
        <PowerUpNextServiceSection />
        <Contactus />
      </main>
    </>
  )
}

export async function getStaticProps(context: any) {
  const { locale } = context

  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  }
}
