import Head from 'next/head'
import Link from "next/link";
import Header from "@/components/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Page Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="not-found-page">
        <Header />
        <section className="grid place-items-center px-6 py-24 sm:py-32 lg:px-8 min-h-[calc(100vh-128px)]">
          <div className="text-center">
            <p className="text-base font-semibold text-darker">404</p>
            <h1 className="mt-4 text-3xl font-bold tracking-tight text-gray-900 sm:text-5xl">Page not found</h1>
            <p className="mt-6 text-base leading-7 text-gray-600">Sorry, we couldn’t find the page you’re looking
              for.</p>
            <div className="mt-10 flex items-center justify-center gap-x-6">
              <Link href="/"
                 className="btn bg-secondary text-white">Go
                back home</Link>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
