import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import BannerSection from "@/components/pages/home/BannerSection";
import ProductsSection from "@/components/pages/home/ProductsSection";
import ProcessSection from "@/components/process";
import CaseSection from "@/components/pages/home/CaseSection";
import NutshellSection from "@/components/pages/home/NutshellSection";
import AdvantageSection from "@/components/pages/home/AdvantageSection";
import ChampionsSection from "@/components/pages/home/ChampionsSection";
import BlogsSection from "@/components/pages/home/BlogsSection";
import Contactus from "@/components/contact-us";

export default function Home() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <BannerSection />
        <ProductsSection />
        <ProcessSection />
        <CaseSection />
        <NutshellSection />
        <AdvantageSection />
        <ChampionsSection />
        <BlogsSection />
        <Contactus />
      </main>
    </>
  )
}

export async function getStaticProps(context: any) {
  const { locale } = context

  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  }
}
