import Head from "next/head";
import Contactus from "@/components/contact-us";
import AboutUsBannerSection from "@/components/pages/about-us/AboutUsBannerSection";
import AboutUsOverviewSection from "@/components/pages/about-us/AboutUsOverviewSection";
import AboutUsTeamSection from "@/components/pages/about-us/AboutUsTeamSection";
import AboutUsApplySection from "@/components/pages/about-us/AboutUsApplySection";
import AboutUsGuideSection from "@/components/pages/about-us/AboutUsGuideSection";
import AboutUsProcessSection from "@/components/pages/about-us/AboutUsProcessSection";

export default function AboutUs() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <AboutUsBannerSection />
        <AboutUsOverviewSection />
        <AboutUsTeamSection />
        <AboutUsApplySection />
        <AboutUsGuideSection />
        <AboutUsProcessSection />
        <Contactus />
      </main>
    </>
  )
}
