import Head from "next/head";
import DesignBannerSection from "@/components/pages/design/DesignBannerSection";
import DesignCategorySection from "@/components/pages/design/DesignCategorySection";
import DesignTeamSection from "@/components/pages/design/DesignTeamSection";
import DesignCaseStudiesSection from "@/components/pages/design/DesignCaseStudiesSection";
import DesignBlogSection from "@/components/pages/design/DesignBlogSection";
import DesignNextServiceSection from "@/components/pages/design/DesignNextServiceSection";
import Contactus from "@/components/contact-us";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";

export default function Design() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <DesignBannerSection />
        <DesignCategorySection />
        <DesignTeamSection />
        <DesignCaseStudiesSection />
        <DesignBlogSection />
        <DesignNextServiceSection />
        <Contactus />
      </main>
    </>
  )
}

export async function getStaticProps(context: any) {
  const { locale } = context

  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  }
}
