import Head from "next/head";
import Contactus from "@/components/contact-us";
import WebAppDevelopmentBannerSection from "@/components/pages/development/web-apps/WebAppDevelopmentBannerSection";
import WebAppDevelopmentCategorySection from "@/components/pages/development/web-apps/WebAppDevelopmentCategorySection";
import WebAppDevelopmentSoftwareSection from "@/components/pages/development/web-apps/WebAppDevelopmentSoftwareSection";
import WebAppDevelopmentCloudSection from "@/components/pages/development/web-apps/WebAppDevelopmentCloudSection";
import WebAppDevelopmentNextServiceSection
  from "@/components/pages/development/web-apps/WebAppDevelopmentNextServiceSection";
import WebAppDevelopmentAdvantageSection
  from "@/components/pages/development/web-apps/WebAppDevelopmentAdvantageSection";
import WebAppDevelopmentBlogSection from "@/components/pages/development/web-apps/WebAppDevelopmentBlogSection";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";

export default function WebAppDevelopment() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Web Apps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <WebAppDevelopmentBannerSection />
        <WebAppDevelopmentCategorySection />
        <WebAppDevelopmentSoftwareSection />
        <WebAppDevelopmentCloudSection />
        <WebAppDevelopmentAdvantageSection />
        <WebAppDevelopmentBlogSection />
        <WebAppDevelopmentNextServiceSection />
        <Contactus />
      </main>
    </>
  )
}

export async function getStaticProps(context: any) {
  const { locale } = context

  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  }
}
