import Head from "next/head";
import AppStoreBannerSection from "@/components/pages/power-up/app-store/AppStoreBannerSection";
import AppStoreCategorySection from "@/components/pages/power-up/app-store/AppStoreCategorySection";
import AppStoreSubmittingSection from "@/components/pages/power-up/app-store/AppStoreSubmittingSection";
import AppStoreAccountSection from "@/components/pages/power-up/app-store/AppStoreAccountSection";
import AppStoreFinalSection from "@/components/pages/power-up/app-store/AppStoreFinalSection";
import AppStoreServiceSection from "@/components/pages/power-up/app-store/AppStoreServiceSection";
import AppStoreNextServiceSection from "@/components/pages/power-up/app-store/AppStoreNextServiceSection";
import Contactus from "@/components/contact-us";

export default function AppStore() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | App Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <AppStoreBannerSection />
        <AppStoreCategorySection />
        <AppStoreSubmittingSection />
        <AppStoreAccountSection />
        <AppStoreFinalSection />
        <AppStoreServiceSection />
        <AppStoreNextServiceSection />
        <Contactus />
      </main>
    </>
  )
}
