import Head from "next/head";
import UIDesignBannerSection from "@/components/pages/design/ui-design/UIDesignBannerSection";
import UIDesignCategorySection from "@/components/pages/design/ui-design/UIDesignCategorySection";
import UIDesignAttractiveSection from "@/components/pages/design/ui-design/UIDesignAttractiveSection";
import UIDesignExperienceSection from "@/components/pages/design/ui-design/UIDesignExperienceSection";
import UIDesignPreparationSection from "@/components/pages/design/ui-design/UIDesignPreparationSection";
import UIDesignAdvantagesSection from "@/components/pages/design/ui-design/UIDesignAdvantagesSection";
import UIDesignBlogSection from "@/components/pages/design/ui-design/UIDesignBlogSection";
import UIDesignNextServiceSection from "@/components/pages/design/ui-design/UIDesignNextServiceSection";
import Contactus from "@/components/contact-us";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";

export default function UiDesign() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | UI Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <UIDesignBannerSection />
        <UIDesignCategorySection />
        <UIDesignAttractiveSection />
        <UIDesignExperienceSection />
        <UIDesignPreparationSection />
        <UIDesignAdvantagesSection />
        <UIDesignBlogSection />
        <UIDesignNextServiceSection />
        <Contactus />
      </main>
    </>
  )
}

export async function getStaticProps(context: any) {
  const { locale } = context

  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  }
}
