import Head from "next/head";
import CareerBannerSection from "@/components/pages/career/CareerBannerSection";

export default function Career() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Career</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <CareerBannerSection />
        <section className="py-28">
          <div className="container mx-auto px-8 lg:px-0 border-b border-light-grey">
            <div className="grid grid-cols-1 lg:grid-cols-2">
              <div className="lg:w-2/3">
                <h3 className="text-7xl font-bold leading-snug">Become part of an international team</h3>
              </div>
              <div className="lg:w-3/5">
                <p className="leading-relaxed mt-8 text-light-grey">Do you program and are at the top of your game in full-stack development of mobile apps, desktop apps and multi-platform applications?</p>
                <p className="leading-relaxed mt-8 text-light-grey">Then you are exactly the right candidate for our factory headquartered in Salzburg!</p>
                <p className="leading-relaxed mt-8 text-light-grey">We&apos;re looking for talented developers like you to join our team. Browse through our open positions or send us an unsolicited application!</p>
                <p className="leading-relaxed mt-8 text-light-grey">Join us now and contribute your skills and ideas to our dynamic working environment!</p>
              </div>
            </div>
            <div className="grid grid-cols-1 lg:grid-cols-2">
              <div className="lg:w-3/5">
                <h3 className="text-7xl font-bold leading-snug my-28">Open positions</h3>
              </div>
            </div>
          </div>
          <div className="container mx-auto px-8 md:px-0">
            <div className="flex flex-col md:flex-row md:justify-between md:items-center my-8">
              <h4 className="text-4xl text-black font-light mb-8 md:mb-0">Sales Manager (m/f/d)</h4>
              <div className="flex justify-between items-center gap-20">
                <p className="">38.5</p>
                <p className="">Salzburg</p>
                <div className="text-secondary font-bold uppercase text-sm">
                  <span className="border-b-2 border-secondary">MORE INFO</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
