import Head from "next/head";
import Contactus from "@/components/contact-us";
import BackendDevelopmentBannerSection from "@/components/pages/development/backend/BackendDevelopmentBannerSection";
import BackendDevelopmentCategorySection
  from "@/components/pages/development/backend/BackendDevelopmentCategorySection";
import BackendDevelopmentCloudSection from "@/components/pages/development/backend/BackendDevelopmentCloudSection";
import BackendDevelopmentOfferSection from "@/components/pages/development/backend/BackendDevelopmentOfferSection";
import BackendDevelopmentCornerstonesSection
  from "@/components/pages/development/backend/BackendDevelopmentCornerstonesSection";
import BackendDevelopmentNextServiceSection
  from "@/components/pages/development/backend/BackendDevelopmentNextServiceSection";

export default function BackendDevelopment() {
  return (
    <>
      <Head>
        <title>Web and Mobile App | Backend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <BackendDevelopmentBannerSection />
        <BackendDevelopmentCategorySection />
        <BackendDevelopmentCloudSection />
        <BackendDevelopmentCornerstonesSection />
        <BackendDevelopmentOfferSection />
        <BackendDevelopmentNextServiceSection />
        <Contactus />
      </main>
    </>
  )
}
